# Generated by Django 4.0.3 on 2022-03-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employee.role'),
            preserve_default=False,
        ),
    ]
