# Generated by Django 4.0.3 on 2022-03-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_address_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
