# Generated by Django 4.0.3 on 2022-03-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_remove_user_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
