# Generated by Django 4.0.3 on 2022-03-28 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_user_address_user_city_user_country_user_pincode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roleid',
            new_name='role',
        ),
    ]
